### ISSUE TITLE
Issues with craft Craft Pro 3.4/Craft Commerce 3.1.7

### ISSUE THREAD

**Issue by anchovy** [sjelfull/craft-ordernotes#6]
Hi

Great plugin but having a few issues getting it running on our craft setup:

PHP version: 7.2.14
Craft Pro: 3.4
Craft Commerce: 3.1.7
Yii version: 2.0.35
Twig version: 2.12.5

Issues:
1. getFullName() in OrderNotesService.php line 173 is throwing a error:
[error][superbig\ordernotes\services\OrderNotesService::error] Exception: Calling unknown method: craft\commerce\models\Address::getFullName().

Changing the code to works:
```
            $address = $order->getBillingAddress();
            $fullName = $address->fullName;
            if ($fullName === ''){
                $fullName = $address->firstName.' '.$address->lastName;
            }
            $subject = $templates->renderString($settings->notifyEmailSubject, $variables);
            $message = (new Message())
                ->setFrom([$fromEmail => $fromName])
                ->setReplyTo([$fromEmail => $fromName])
                ->setSubject($subject)
                ->setTo([$order->email => $fullName]);
```

2. default $SYSTEM_EMAIL_NAME is coming through as the string '$SYSTEM_EMAIL_NAME'
3. Leaving the 'Email Sender Address' empty throws the error:
[error][superbig\ordernotes\services\OrderNotesService::error] Exception: Address in mailbox given [$SYSTEM_EMAIL_ADDRESS] does not comply with RFC 2822, 3.6.2.

Thanks in advance - if you need any more info please let me know. 
NB - we've purchased a license and this is for a pressing project.

**Comment by sjelfull** [comment]
Thanks for reporting! I'm in the middle of a launch myself, but will try to fit this in within the next few days.

**Comment by anchovy** [comment]
Hi @sjelfull 

Anything I can do to help out, want me to look at a pull request for the first issue, which is the braking issue on commerce v3+ as craft\commerce\models\Address::getFullName() was removed in v3.0.0 

https://github.com/craftcms/commerce/blob/master/CHANGELOG.md#300---2020-01-28

Regards
Ben

**Comment by JonnyBR12** [comment]
Hi @anchovy - did you manage to get this working? We've just installed for a client and order notes are saving but not sending. Is this the problem you had? We're on Craft CMS 3.5.5 with Commerce 3.2.2.1.

**Comment by anchovy** [comment]
Hi @JonnyBR12 check your error logs - I'm sure you'll see the error relating to `craft\commerce\models\Address::getFullName().`

I can fix by manually editing the file _OrderNotesService.php line 173_ as per my initial post which obviously isn't ideal for non-dev environments.

**Comment by JonnyBR12** [comment]
Thanks @anchovy - yeah I tried your fix earlier but no joy so I'll check again and I'll post back if anything's different 👍

**Comment by anchovy** [comment]
@JonnyBR12 odd - anything other errors in the log relating to superbig\ordernotes?

**Comment by JonnyBR12** [comment]
You're spot on with the fix - just had another look into it and the initial error was exactly what you mentioned, however, I missed the error with the .txt template. 

When we use Sprout Email etc we create .txt files and this wouldn't accept that so I changed the text version file to .HTML and all sorted. So using your fix and using the correct file extension works great. 

Thanks again! My bad!

**Comment by anchovy** [comment]
@sjelfull just raised a pull request to fix the breaking issue with Commerce v3+

**Comment by sjelfull** [comment]
Thanks alot, will tag release tomorrow!

**Comment by sjelfull** [comment]
2.0.3 has been released with this fix. Thanks again for the patience!

**Comment by anchovy** [comment]
Hi @sjelfull looks like you also added a dependency for commerce 2 in the push in the _composer.json.

```
    "require": {
        "craftcms/cms": "^3.0.0",
        "craftcms/commerce": "^2.0.0"
    },
```

This dependency is stopping the upgrade when running commerce 3+
```
$ composer require superbig/craft-ordernotes:2.0.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for superbig/craft-ordernotes 2.0.3 -> satisfiable by superbig/craft-ordernotes[2.0.3].
    - superbig/craft-ordernotes 2.0.3 requires craftcms/commerce ^2.0.0 -> satisfiable by craftcms/commerce[2.0.0, 2.0.0-beta.1, 2.0.0-beta.1.1, 2.0.0-beta.1.2, 2.0.0-beta.10, 2.0.0-beta.11, 2.0.0-beta.12, 2.0.0-beta.12.1, 2.0.0-beta.13, 2.0.0-beta.13.1, 2.0.0-beta.14, 2.0.0-beta.15, 2.0.0-beta.2, 2.0.0-beta.3, 2.0.0-beta.4, 2.0.0-beta.4.1, 2.0.0-beta.5, 2.0.0-beta.6, 2.0.0-beta.7, 2.0.0-beta.8, 2.0.0-beta.8.1, 2.0.0-beta.9, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.0.1, 2.1.0.2, 2.1.1, 2.1.1.1, 2.1.10, 2.1.11, 2.1.12, 2.1.12.1, 2.1.13, 2.1.2, 2.1.3, 2.1.3.1, 2.1.4, 2.1.5, 2.1.5.1, 2.1.5.2, 2.1.6, 2.1.6.1, 2.1.7, 2.1.8, 2.1.9, 2.2.0, 2.2.1, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.14, 2.2.15, 2.2.16, 2.2.17, 2.2.18, 2.2.19, 2.2.2, 2.2.20, 2.2.21, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

Think this should be one of the following:
```
    "require": {
        "craftcms/cms": "^3.0.0",
        "craftcms/commerce": >=2.0.0"
    },
```

Or the below to constrain commerce to v2 or v3.
```
    "require": {
        "craftcms/cms": "^3.0.0",
        "craftcms/commerce": >=2.0.0,<4.0.0"
    },
```

**Comment by sjelfull** [comment]
@anchovy Woops. Tagged new release with your change.
